###모든 포스팅 보기
GET localhost:3000/posts

###포스팅 상세보기
GET localhost:3000/posts/2

###포스팅 작성
POST localhost:3000/posts
Content-Type: application/json

{
  "content": "아주 엄청난 맛집이군요",
  "rating": 5,
  "img": "img_url",
  "visibility": "public"
}

###포스팅 수정
PUT localhost:3000/posts/4
Content-Type: application/json

{
  "content": "아주 엄청난 맛집이군요",
  "visibility": "private"
}

###포스팅 삭제
DELETE localhost:3000/posts/4

###포스팅 좋아요
POST localhost:3000/posts/2/like
Content-Type: application/json

{
  "userId": 1
}

###특정 게시글에 해당하는 모든 댓글 보기
GET localhost:3000/posts/2/comments

###댓글 작성
POST localhost:3000/posts/2/comments
Content-Type: application/json

{
  "content": "아주 엄청난 맛집이군요"
}

###댓글 수정
PUT localhost:3000/posts/1/comments/1
Content-Type: application/json

{
  "content": "사실 별로였습니당"
}

###댓글 삭제
DELETE localhost:3000/posts/1/comments/8

###댓글 좋아요
POST localhost:3000/posts/2/comments/5/like
Content-Type: application/json

{
  "userId": 1
}

